export const AuthenAction = {
  AUTHEN_LOGIN_R: 'AUTHEN_LOGIN_R',
  AUTHEN_LOGIN_S: 'AUTHEN_LOGIN_S',
  AUTHEN_LOGOUT_R: 'AUTHEN_LOGOUT_R',
  AUTHEN_LOGOUT_S: 'AUTHEN_LOGOUT_S',
  REGISTER_R: 'REGISTER_R',
};